export const TYPE_TO_NAME: Record<string, string> = {
    "uint256": "256-bit Unsigned Integer",
    "uint128": "128-bit Unsigned Integer",
    "uint64": "64-bit Unsigned Integer",
    "uint32": "32-bit Unsigned Integer",
    "uint16": "16-bit Unsigned Integer",
    "uint8": "8-bit Unsigned Integer",
    "int256": "256-bit Signed Integer",
    "int128": "128-bit Signed Integer",
    "int64": "64-bit Signed Integer",
    "int32": "32-bit Signed Integer",
    "int16": "16-bit Signed Integer",
    "int8": "8-bit Signed Integer",
    "address": "Ethereum Address",
    "bool": "Boolean",
    "string": "String",
    "bytes": "Byte Array",
    "bytes1": "1-Byte Array",
    "bytes2": "2-Byte Array",
    "bytes3": "3-Byte Array",
    "bytes4": "4-Byte Array",
    "bytes5": "5-Byte Array",
    "bytes6": "6-Byte Array",
    "bytes7": "7-Byte Array",
    "bytes8": "8-Byte Array",
    "bytes9": "9-Byte Array",
    "bytes10": "10-Byte Array",
    "bytes11": "11-Byte Array",
    "bytes12": "12-Byte Array",
    "bytes13": "13-Byte Array",
    "bytes14": "14-Byte Array",
    "bytes15": "15-Byte Array",
    "bytes16": "16-Byte Array",
    "bytes17": "17-Byte Array",
    "bytes18": "18-Byte Array",
    "bytes19": "19-Byte Array",
    "bytes20": "20-Byte Array",
    "bytes21": "21-Byte Array",
    "bytes22": "22-Byte Array",
    "bytes23": "23-Byte Array",
    "bytes24": "24-Byte Array",
    "bytes25": "25-Byte Array",
    "bytes26": "26-Byte Array",
    "bytes27": "27-Byte Array",
    "bytes28": "28-Byte Array",
    "bytes29": "29-Byte Array",
    "bytes30": "30-Byte Array",
    "bytes31": "31-Byte Array",
    "bytes32": "32-Byte Array",
}

export const TYPE_TO_PATTERN: Record<string, string> = {
    "uint256": "^[0-9]+$",
    "uint128": "^[0-9]+$",
    "uint64": "^[0-9]+$",
    "uint32": "^[0-9]+$",
    "uint16": "^[0-9]+$",
    "uint8": "^[0-9]+$",
    "int256": "^-?[0-9]+$",
    "int128": "^-?[0-9]+$",
    "int64": "^-?[0-9]+$",
    "int32": "^-?[0-9]+$",
    "int16": "^-?[0-9]+$",
    "int8": "^-?[0-9]+$",
    "address": "^0x[0-9a-fA-F]{40}$",
    "bool": "^(true|false)$",
    "string": ".*",
    "bytes": ".*",
    "bytes1": ".*",
    "bytes2": ".*",
    "bytes3": ".*",
    "bytes4": ".*",
    "bytes5": ".*",
    "bytes6": ".*",
    "bytes7": ".*",
    "bytes8": ".*",
    "bytes9": ".*",
    "bytes10": ".*",
    "bytes11": ".*",
    "bytes12": ".*",
    "bytes13": ".*",
    "bytes14": ".*",
    "bytes15": ".*",
    "bytes16": ".*",
    "bytes17": ".*",
    "bytes18": ".*",
    "bytes19": ".*",
    "bytes20": ".*",
    "bytes21": ".*",
    "bytes22": ".*",
    "bytes23": ".*",
    "bytes24": ".*",
    "bytes25": ".*",
    "bytes26": ".*",
    "bytes27": ".*",
    "bytes28": ".*",
    "bytes29": ".*",
    "bytes30": ".*",
    "bytes31": ".*",
    "bytes32": ".*",
}
